<?php

session_start();

include 'repository/connection.php';

$error = '';

// Check if the user filled the form :
if (!empty($_POST)) {
    $db = connectToDataBase();
    
    // We stock the values filled by the user in a variable : 
    $username = $_POST['username'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    
    // Regex for the security of the password & email :
    $regexEmail = '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/'; // generated by the AI
    $regexPassword = '/^(?=.*[a-z])(?=.*[A-Z])(?=.*[\W_]).{12,}$/'; // generated by the AI 
    
    // We check the security and then if the email is not already used to register him:
    if (!preg_match($regexEmail, $email)) {
        $error = 'Veuillez saisir une adresse email valide.';
    }
    elseif (!preg_match($regexPassword, $password)) {
        $error = 'Votre mot de passe doit contenir au moins 12 caractères dont au moins une majuscule, un chiffre et un caractère spécial';
    }
    elseif (getUserByEmail($email)) {
        $error = 'Cette adresse email est déjà utilisée.';
    }
    else {
        $passwordHashed = password_hash($password, PASSWORD_DEFAULT);
        
        // we stock the informations of the user to insert him :
        /* $user = [
            'username' => $username,
            'email' => $email,
            ]; */
    }
}

// Integration of the layout & template:
$layoutTitle = 'Akinator Jeu - Inscription';
$template = 'templates/signup.phtml';
include 'layout/layout.phtml';
