<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/style.css">
    <meta description="Jeu d'Akinator dans lequel tu tentes de faire deviner quelque chose à l'intelligence artificielle">
    <title><?= (isset($layoutTitle))?$layoutTitle:'Akinator | Jeu'; ?></title>
</head>
<body>
    <header>
        <div class="logo-home">
            <a href="index.php">Accueil</a>
        </div>
        <nav>
            
            <a href="login.php">Connexion</a>
            <a href="signup.php">Inscription</a>
        </nav>
    </header>
    
    <main>
        <?php include $template; ?>
    </main>
    
    <footer>
        <p>&copy; 2026 3W Academy - All rights reserved</p>
    </footer>
</body>
</html>