<div class="my-account-page">
    <h1><?= htmlspecialchars($_SESSION['username']); ?></h1>

    <div class="my-account-card">
        <section class="account-section">
            <h2>Historique des parties</h2>


            <?php if (!empty($historyGames)) : ?>
                <ul class="history-list">
                    <?php foreach ($historyGames as $game) : ?>
                        <li>
                            <strong><?= htmlspecialchars($game['name']) ?></strong>
                            <span><?= htmlspecialchars($game['played_date']) ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else : ?>
                <p>Aucune partie enregistrée pour le moment.</p>
            <?php endif; ?>

            <?php if (!empty($successUpdatePassword)) : ?>
                <p class="success"><?= htmlspecialchars($successUpdatePassword) ?></p>
            <?php endif; ?>

            <?php if (!empty($error)) : ?>
                <p class="error"><?= htmlspecialchars($error) ?></p>
            <?php endif; ?>
        </section>


        <section class="account-section">
            <h2>Changer mon mot de passe</h2>

            <form method="POST">
                <label for="current-password">Mot de passe actuel</label>
                <input type="password" name="current-password" id="current-password" required>

                <label for="new-password">Nouveau mot de passe</label>
                <input type="password" name="new-password" id="new-password" required>

                <button type="submit" name="change-password">
                    Changer de mot de passe
                </button>
            </form>
        </section>

      
        <section class="account-section delete-section">
            <h2>Supprimer mon compte</h2>

            <form method="POST">
                <button type="submit" name="delete-account" class="delete-btn">
                    Supprimer mon compte
                </button>
            </form>
        </section>

    </div>
</div>
